#!/bin/bash
#
# Calculate lines of code for the project.
# This script runs 'cloc' on the parent directory,
# excluding non-source files such as JSON, XML, HTML, CSS, etc.
#

generate_manual_files() {
  cd "hal.guru-docs"
  echo "Generating manual files for $version"

  echo "## Manual files" >> "$summary_file"
  echo "" >> "$summary_file"
  echo "Documentation for core version $version" >> "$summary_file"
  echo "" >> "$summary_file"
  ./halguru-generate-manual.sh > /dev/null

  echo "✺ Autogenerated files ('autogen-' prefix)" >> "$summary_file"
  echo "" >> "$summary_file"

  echo "| Directory | Markdown Files | Markdown Lines | Autogen✺ Files | Autogen✺ Lines |" >> "$summary_file"
  echo "|-----------|---------------:|---------------:|---------------:|---------------:|" >> "$summary_file"
  #directories=($(find "docs" -mindepth 1 -maxdepth 1 -type d))
  #for dir in "${directories[@]}"; do
  #  local files_count=$(find "$dir" \( -name .git -o -name .idea -o -name site -o -name public -o -name resources -o -name __pycache__ \) -type d -prune -o -type f -name "*.md" | wc -l)
  #  local lines_count=$(find "$dir" \( -name .git -o -name .idea -o -name site -o -name public -o -name resources -o -name __pycache__ \) -type d -prune -o -type f -name "*.md" -exec wc -l {} + | awk '{sum += $1} END {print sum}')
  #  local autogen_files_count=$(find "$dir" \( -name .git -o -name .idea -o -name site -o -name public -o -name resources -o -name __pycache__ \) -type d -prune -o -type f -name "autogen-*.md" | wc -l)
  #  local autogen_lines_count=$(find "$dir" \( -name .git -o -name .idea -o -name site -o -name public -o -name resources -o -name __pycache__ \) -type d -prune -o -type f -name "autogen-*.md" -exec wc -l {} + | awk '{sum += $1} END {print sum}')
  #  if [ "$files_count" -gt 0 ]; then
  #    echo "| $dir | $files_count | $lines_count | $autogen_files_count | $autogen_lines_count |" >> "$summary_file"
  #  fi
  #done
  local files_count=$(count_files . "*.md")
  local lines_count=$(count_lines . "*.md")
  local autogen_files_count=$(count_files . "autogen-*.md")
  local autogen_lines_count=$(count_lines . "autogen-*.md")
  if [ "$files_count" -gt 0 ]; then
    echo "| docs | $files_count | $lines_count | $autogen_files_count | $autogen_lines_count |" >> "$summary_file"
  fi
  echo "" >> "$summary_file"
  cd ..
}

build_find_name_expr() {
  local input="$1"
  local -a items
  local i
  local -a result

  IFS=';' read -r -a items <<< "$input"

  for i in "${!items[@]}"; do
    # Skip empty items (e.g. from trailing semicolon or empty input)
    [[ -z "${items[$i]}" ]] && continue
    if [ "${#result[@]}" -gt 0 ]; then
      result+=( -o )
    fi
    result+=( -name "${items[$i]}" )
  done

  # Return array as quoted elements
  printf "%q " "${result[@]}"
}

count_files() {
  local search_dir="${1:-.}"
  local file_patterns="${2:-*.*}"
  local exclude_directories="${3:-.git;.idea;site;public;resources;__pycache__;bin;obj;images;img;sprites;webfonts;svgs;static}"

  local -a find_expr
  local -a prune_expr

  # Read results into arrays
  eval "find_expr=($(build_find_name_expr "$file_patterns"))"
  eval "prune_expr=($(build_find_name_expr "$exclude_directories"))"

  local -a find_cmd=(find "$search_dir")

  if [ "${#prune_expr[@]}" -gt 0 ]; then
    find_cmd+=( \( "${prune_expr[@]}" \) -type d -prune -o )
  fi

  find_cmd+=( -type f )

  if [ "${#find_expr[@]}" -gt 0 ]; then
    find_cmd+=( \( "${find_expr[@]}" \) )
  fi

  find_cmd+=( -print )

  "${find_cmd[@]}" | wc -l
}

count_lines() {
  local search_dir="${1:-.}"
  local file_patterns="${2:-*.*}"
  local exclude_directories="${3:-.git;.idea;site;public;resources;__pycache__;bin;obj;images;img;sprites;webfonts;svgs;static}"

  local -a find_expr
  local -a prune_expr

  # Read results into arrays
  eval "find_expr=($(build_find_name_expr "$file_patterns"))"
  eval "prune_expr=($(build_find_name_expr "$exclude_directories"))"

  local -a find_cmd=(find "$search_dir")

  if [ "${#prune_expr[@]}" -gt 0 ]; then
    find_cmd+=( \( "${prune_expr[@]}" \) -type d -prune -o )
  fi

  find_cmd+=( -type f )

  if [ "${#find_expr[@]}" -gt 0 ]; then
    find_cmd+=( \( "${find_expr[@]}" \) )
  fi

  find_cmd+=( -exec wc -l {} + )

  "${find_cmd[@]}" | awk '{sum += $1} END {print sum + 0}'
}

generate_git_information() {
  echo "Generating Git information for repositories"

  echo "## Git Information" >> "$summary_file"
  echo "" >> "$summary_file"

  generate_git_table_header
  generate_git_table_row "hal.guru-robots-core"
  generate_git_table_row "hal.guru-apps"
  generate_git_table_row "hal.guru-licensing"
  generate_git_table_row "hal.guru-maui"
  generate_git_table_row "hal.guru-docs"
  generate_git_table_row "hal.guru-website"
  generate_git_table_row "hal.guru-content"
  #generate_git_table_row "hal.guru-marketing"
  #generate_git_table_row "hal.guru-management"

  echo "" >> "$summary_file"
}

generate_git_table_header() {
  echo "✺ Lines of code" >> "$summary_file"
  echo "" >> "$summary_file"
  echo "| Repository | Commits | Files  | Total✺ | Added✺ | Deleted✺ | Created | Updated |" >> "$summary_file"
  echo "|------------|--------:|-------:|-------:|-------:|----------|---------|---------|" >> "$summary_file"
}

generate_git_table_row() {
  local repo_name="$1"
  echo "- '$repo_name'"
  cd "$repo_name" || return
  dotnet clean *.sln > /dev/null 2>&1
  local total_stats=$(git -c diff.renameLimit=32768 log --shortstat --pretty=format: | \
                      awk '{
                        for (i = 1; i <= NF; i++) {
                          if ($i ~ /insertion/) add += $(i-1)
                          if ($i ~ /deletion/) del += $(i-1)
                        }
                      }
                      END {
                        print (add + 0), " | ", (del + 0)
                      }')
  #local last_month_stats=$(git log --since="1 month ago" --shortstat --pretty=format: | \
  #  awk '/insertions/ {add += $4} /deletions/ {del += $6} END {print add, "/", del}')
  #local last_week_stats=$(git log --since="1 week ago" --shortstat --pretty=format: | \
  #  awk '/insertions/ {add += $4} /deletions/ {del += $6} END {print add, "/", del}')
  local total_commits=$(git log --format="%H" | wc -l)
  local created_date=$(git log --reverse --format=%ad --date=format:'%Y-%m-%d' | head -n 1)
  local updated_date=$(git log -1 --format=%ad --date=format:'%Y-%m-%d')
  local files_count=$(count_files)
  local lines_count=$(count_lines)
  local name="${repo_name:9}"
  echo "| $name | $total_commits | $files_count | $lines_count | $total_stats | $created_date | $updated_date |" >> "$summary_file"
  cd ..
}

function generate_front_matter() {
  echo "---" >> "$summary_file"
  echo "title: Project Summary for $current_date" >> "$summary_file"
  echo "description: Current status of the hal.guru project - quantitative metrics like lines of code, commits, and overall progress." >> "$summary_file"
  echo "autogenerated: true" >> "$summary_file"
  echo "core_version: $version" >> "$summary_file"
  echo "last_update: $current_date" >> "$summary_file"
  echo "---" >> "$summary_file"
  echo "" >> "$summary_file"
}

function generate_file_header() {
  echo "Current status of the hal.guru project for $current_date." >> "$summary_file"
  echo "Quantitative metrics like lines of code, commits, and overall progress." >> "$summary_file"
  echo "" >> "$summary_file"
}

function generate_footer_information() {
  echo "## Technical Information" >> "$summary_file"
  echo "" >> "$summary_file"
  echo "This file is generated by [halguru_generate-project-summary.sh](https://github.com/HAL-guru/hal.guru-docs/blob/main/halguru-generate-project-summary.sh) tool." >> "$summary_file"
  echo "" >> "$summary_file"
}

function generate_cloc_summary() {
  echo "Genrating lines of code"
  echo "## Lines of code summary" >> "$summary_file"
  echo "" >> "$summary_file"
  #cloc . --not-match-f='\.json$|\.xml$|\.html$|\.css$|\.svg$|\.js$|\.yaml$|\.txt$|\.yml$|\.ini$|\.less$|\.scss$' --exclude_directories-dir=.git,.idea,site,public,resources,__pycache__ >> "$summary_file"
  echo "\`\`\`" >> "$summary_file"
  cloc . --exclude-dir=.git,.idea,site,public,resources,__pycache__ >> "$summary_file"
  echo "\`\`\`" >> "$summary_file"
}

current_dir=$(pwd)
current_date="$(date +%F)"
summary_file="$current_dir/docs/status/project-summary.md"
copyright=$(halguru --version)
version=$(awk '{print $2}' <<< "$copyright")

trap 'cd "$current_dir";' EXIT

echo "Generating 'project-summary.md' file"
: > "$summary_file"

cd ..

generate_front_matter
generate_file_header
generate_manual_files
generate_git_information
generate_cloc_summary
generate_footer_information

echo "Done. Check file '$summary_file'"
