#!/bin/bash
#
# Calculate lines of code for the project.
# This script runs 'cloc' on the parent directory,
# excluding non-source files such as JSON, XML, HTML, CSS, etc.
#

generate_manual_files() {
  cd "hal.guru-docs"
  version=$(halguru --version)
  echo "Generating manual files for $version"

  echo "## Manual files" >> "$summary_file"
  echo "" >> "$summary_file"
  echo "$version" >> "$summary_file"
  echo "" >> "$summary_file"
  ./halguru-generate-manual.sh > /dev/null

  echo "| Directory | Markdown Files | Lines Count |" >> "$summary_file"
  echo "|-----------|---------------:|------------:|" >> "$summary_file"
  directories=($(find "docs" -mindepth 1 -maxdepth 1 -type d))
  for dir in "${directories[@]}"; do
    local files_count=$(find "$dir" -type f -name "*.md" | wc -l)
    local lines_count=$(find "$dir" -type f -name "*.md" -exec wc -l {} + | awk '{sum += $1} END {print sum}')
    if [ "$files_count" -gt 0 ]; then
      echo "| $dir | $files_count | $lines_count |" >> "$summary_file"
    fi
  done
  cd ..
}

generate_git_information() {
  echo "Generating Git information for repositories"

  echo "## Git Information" >> "$summary_file"
  echo "" >> "$summary_file"

  generate_git_table_header
  generate_git_table_row "hal.guru-robots-core"
  generate_git_table_row "hal.guru-apps"
  generate_git_table_row "hal.guru-licensing"
  generate_git_table_row "hal.guru-maui"
  generate_git_table_row "hal.guru-docs"
  generate_git_table_row "hal.guru-website"
  generate_git_table_row "hal.guru-content"
  generate_git_table_row "hal.guru-marketing"
  generate_git_table_row "hal.guru-management"
}

generate_git_table_header() {
  echo "✺ Lines of code" >> "$summary_file"
  echo "" >> "$summary_file"
  echo "| Repository | Commits | Total✺ | Added✺ | Deleted✺ | Created | Updated |" >> "$summary_file"
  echo "|------------|--------:|-------:|-------:|----------:|--------|---------|" >> "$summary_file"
}

generate_git_table_row() {
  local repo_name="$1"
  echo "- '$repo_name'"
  cd "$repo_name" || return
  dotnet clean *.sln > /dev/null 2>&1
  local total_stats=$(git -c diff.renameLimit=32768 log --shortstat --pretty=format: | \
    awk '/insertions/ {add += $4} /deletions/ {del += $6} END {print add, " | ", del}')
  #local last_month_stats=$(git log --since="1 month ago" --shortstat --pretty=format: | \
  #  awk '/insertions/ {add += $4} /deletions/ {del += $6} END {print add, "/", del}')
  #local last_week_stats=$(git log --since="1 week ago" --shortstat --pretty=format: | \
  #  awk '/insertions/ {add += $4} /deletions/ {del += $6} END {print add, "/", del}')
  local total_commits=$(git log --format="%H" | wc -l)
  local created_date=$(git log --reverse --format=%ad --date=format:'%Y-%m-%d' | head -n 1)
  local updated_date=$(git log -1 --format=%ad --date=format:'%Y-%m-%d')
  local lines_count=$(
    find . -type f \( \
      -name "*.md" -o \
      -name "*.cs" -o \
      -name "*.yaml" -o \
      -name "*.yml" \
      -name "*.csproj" \
      -name "*.sln" \
      -name "*.sh" \
      -name "*.cshtml" \
      -name "*.razor" \
    \) -exec wc -l {} + | awk '{sum += $1} END {print sum}'
  )
  echo "| $repo_name | $total_commits | $lines_count | $total_stats | $created_date | $updated_date |" >> "$summary_file"
  cd ..
}

function generate_front_matter() {
  : > "$summary_file"
  echo "---" >> "$summary_file"
  echo "title: Project Summary for $current_date" >> "$summary_file"
  echo "description: Current status of the hal.guru project - quantitative metrics like lines of code, commits, and overall progress." >> "$summary_file"
  echo "autogenerated: true" >> "$summary_file"
  echo "last_update: $current_date" >> "$summary_file"
  echo "---" >> "$summary_file"
  echo "" >> "$summary_file"
}

function generate_file_header() {
  echo "Current status of the hal.guru project for $current_date. Quantitative metrics like lines of code, commits, and overall progress." >> "$summary_file"
  echo "" >> "$summary_file"
}

current_dir=$(pwd)
current_date="$(date +%F)"
summary_file="$current_dir/docs/project-summary.md"

trap 'cd "$current_dir";' EXIT

echo "Generating 'docs/project-summary.md' file"
: > "$summary_file"

cd ..

generate_front_matter
generate_file_header
generate_git_information

echo "Calculating lines of code"
#cloc . --not-match-f='\.json$|\.xml$|\.html$|\.css$|\.svg$|\.js$|\.yaml$|\.txt$|\.yml$|\.ini$|\.less$|\.scss$' >> "$summary_file"

generate_manual_files
echo "Done. Check file $summary_file"
