site_name: docs.hal.guru
site_url: https://docs.hal.guru/
site_author: hal.guru
site_description: >-
  AI Agents that works, for you
repo_name: Admin
repo_url: https://admin.hal.guru
copyright: '&copy; 2025 hal.guru sp. z o.o.'
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HAL-guru/hal.guru-docs
      name: hal.guru on GitHub
  title: docs.hal.guru
theme:
  name: material
  logo: icon-white.png
  favicon: favicon.svg
  icon:
    repo: material/account
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    #- navigation.instant
    #- navigation.tabs
    #- navigation.sections
    #- navigation.expand
    - navigation.top
    - navigation.tracking
    #- navigation.footer (next/previous page)
    #- toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.tabbed
    - admonition
    - attr_list
    - def_list
    - md_in_html
    - edit_uri
  extra_css:
    - overrides/custom.css
  custom_dir: overrides
extra_javascript:
  - js/platform-status.js
markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
plugins:
  - search
  - macros:
      on_undefined: lax
      include_dir: .
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
      fallback_to_build_date: true
      locale: en
      timezone: Europe/Warsaw
nav:
  - 'Welcome': 'index.md'
  - 'Installation': 'installation/index.md'
  - 'Getting Started': 'getting-started/index.md'
  - 'CLI Application': 'cli/index.md'
  - 'AI Agent Config': 'agent-configuration/index.md'
  - 'Schemas': 'schemas/index.md'
  - 'Status': 'status.md'
